### PR TITLE
feat: native Hysteria2 outbound handler via daeuniverse/outbound

### PR DESCRIPTION
**Pull request by gqcdm**
## Summary

Replace plugin-based Hysteria2 (socks5 outbound -> external binary via PluginChain) with native xray-core integration using the already-included `daeuniverse/outbound` library (zero new dependencies).

### New: `core/hint/proxy/hysteria2/`
- `config.proto` - protobuf ClientConfig with 9 fields (address, password, sni, allow_insecure, pinned_certchain_sha256, obfs, obfs_password, up_mbps, down_mbps)
- `config.pb.go` - generated protobuf Go code
- `outbound.go` - native outbound handler following the TUIC pattern

### Modified
- **`core/hint/conf/loader.go`** - register hysteria2 in `customProtocols` map + `buildCustomOutbounds` switch case
- **`core/main/distro/all/all.go`** - import `hint/proxy/hysteria2`
- **`service/kernel/serverObj/hysteria2.go`** - rewritten from plugin mode to native mode:
  - `NeedPluginPort()` returns `false` (no external process)
  - `Configuration()` produces `CoreOutbound` with `Inlined` JSON settings
  - Properly extracts password, SNI, bandwidth, and TLS params from the URL
- **`service/kernel/serverObj/anytls.go`** - fix SNI parameter: accept `peer` query param as fallback

## Design
- **Zero new dependencies** - daeuniverse/outbound v0.0.0-20250722064253 is already in go.mod
- Follows established TUIC/AnyTLS patterns for Inlined settings, customProtocols, and outbound handler architecture
- Obfuscation (Salamander) and cert pinning proto fields are reserved for forward compatibility

## Breaking Changes
- Configurations using hysteria2 with plugin mode will need to be re-imported (external plugin binary is no longer required)

### CODE REVIEW

**Comment by MangoIsIllegal** [comment]
First of all, thank you for this PR — the approach of using daeuniverse/outbound to add native Hysteria2 support is exactly the right direction.

However, I tried building this PR and hit a dependency conflict that prevents compilation. The root cause is a **qpack version incompatibility** between two quic-go forks:

## The Conflict

1. `github.com/daeuniverse/quic-go` (required by `daeuniverse/outbound`) calls:
   - `qpack.NewDecoder(func(hf qpack.HeaderField))` — expects a callback argument
   - `decoder.DecodeFull(...)` — method that only exists in older qpack versions

2. `github.com/apernet/quic-go` (required by `github.com/xtls/xray-core` for Hysteria2 transport) calls:
   - `qpack.NewDecoder()` — no arguments (new API)
   - `decoder.Decode(...)` + `qpack.DecodeFunc` — new API surface

Both import `github.com/quic-go/qpack` but require **mutually incompatible API versions**:
- qpack v0.5.x has `NewDecoder(callback)` + `DecodeFull` (what daeuniverse/quic-go needs)
- qpack v0.6.0 has `NewDecoder()` + `Decode` + `DecodeFunc` (what apernet/quic-go needs)

Since Go modules only allow one version of a given import path, there is no single qpack version that satisfies both consumers.

## Reproduction

```bash
git clone https://github.com/v2rayA/v2rayA.git
cd v2rayA
git fetch origin pull/1898/head:pr-1898
git checkout pr-1898
git submodule update --init --recursive

cd core
docker run --rm -v $(pwd):/src -w /src \
  -e GOOS=linux -e GOARCH=amd64 -e CGO_ENABLED=0 \
  golang:1.26-alpine \
  go build -o /src/v2raya_core -trimpath ./main/
```

Build errors:
```
# github.com/daeuniverse/quic-go/http3
/go/pkg/mod/github.com/daeuniverse/quic-go@v0.0.0-20250210145620-2083199a7851/http3/client.go:96:31: too many arguments in call to qpack.NewDecoder
    have (func(hf qpack.HeaderField))
    want ()
/go/pkg/mod/github.com/daeuniverse/quic-go@.../http3/conn.go:140:27: c.decoder.DecodeFull undefined

# github.com/apernet/quic-go/http3
/go/pkg/mod/github.com/apernet/quic-go@v0.59.1-0.20260425001925-6c6cc9bcb716/http3/headers.go:53:34: undefined: qpack.DecodeFunc
/go/pkg/mod/github.com/apernet/quic-go@.../http3/client.go:103:23: not enough arguments in call to qpack.NewDecoder
    have ()
    want (func(f qpack.HeaderField))
```

## Possible Fix

The core issue is that `daeuniverse/quic-go` is a fork that hasn't been updated to match the upstream `quic-go` API changes around qpack v0.6.0. To make this PR compile, one of these would be needed:

1. Update `daeuniverse/outbound` (and its `daeuniverse/quic-go` dependency) to be compatible with `qpack v0.6.0`, or
2. Downgrade `apernet/quic-go` in xray-core to a version that uses the old qpack API (may not be feasible since xray-core requires the newer version), or
3. Use a `replace` directive to point `daeuniverse/quic-go` to a patched version that works with qpack v0.6.0.

Hope this helps. The architecture is sound — just the dependency graph needs to be reconciled.

**Comment by MarksonHon** [comment]
Thanks for your work, however, Xray-core itself supports Hysteria2, so I fixed it in https://github.com/v2rayA/v2rayA/pull/1924. This pull request will be closed, thanks for your work again.
